import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { classNames } from "@/functions/classnames";
import Navbar from "@/components/navBar";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={classNames(
          montserrat.className,
          "flex flex-col min-h-screen"
        )}
      >
        <Navbar />
        <div className="flex flex-col flex-grow mt-24">{children}</div>
      </body>
    </html>
  );
}
